Wolf:
  lethality: 0.85
  radius_m: 6.0
  persistence: "static"
  

Cow:
  lethality: -0.05
  radius_m: 1.0
  persistence: "static"
  

wasp:
  lethality: 0.30
  radius_m: 2.0
  persistence: "static"
 